### ISSUE TITLE
issue with connecting things

### ISSUE THREAD

**Issue by blahblahblahhh** [blahblahblahhh/t8ble#1]
i cannot get my orders to show up. everything is connected i think, it was working 100% fine. then i changed something, i don't know what it was and i have no idea what's wrong now. i have tried everything. i just need help understanding WHERE the error is coming from. i even accessed a version of the app i had saved previously and am getting the same error, which makes no sense to me??? WHY IS IT SAYING THINGS DON'T EXIST WHEN THEY DO

**Comment by blahblahblahhh** [comment]
i have no idea how this assigning ppl thing works

**Comment by blahblahblahhh** [comment]
sorry in advance

**Comment by rapala61** [comment]
in person

**Comment by blahblahblahhh** [comment]
THANK YOU RAFA
